server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #\u58F0\u660E\u81EA\u5DF1\u662F\u4E2A\u670D\u52A1\u7AEF\uFF0C\u6240\u4EE5\u4E0D\u9700\u8981\u6CE8\u518C\u8FDB\u670D\u52A1
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/